### ISSUE TITLE
Generate UMD version of arthemis. 

### ISSUE THREAD

**Issue by parga** [munizart/arthemis#7]
since this can be used in the front end (ES6 import) or the backend (CommonJS) or even AMD (RequireJS) we need to make the module flexible enough to be able to be imported .

UMD provides the wrapper to do so.

**Comment by parga** [comment]
@munizart let me know if that makes sense. also will allow us to use something like jest for testing

**Comment by parga** [comment]
@PatoCinza please review

**Comment by munizart** [comment]
@parga Thanks again for contributing, that would be a really nice feature to ship
@PatoCinza would you mind reviewing #10 ?
